# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72edfcc2f7efc73660be5f91f195cdca5f99f1a0b7038ff5436825f45f27a4a7cbd1a6a833a7a69f4d4ccb46a741c348db8e0ee4dcda49830f6f5a182cf7a9f0

test:
  secret_key_base: 4f043c19ccbe1a46f173e8e5e65aef8e8ccc3335bc98bbd57bf222f5f5badbf9089958f0bb5a0e24b08fc01935215524406bcf36ecd6fac515c64b5aa3f1a65c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
